def generate(deathee, deather):
  return [
    f"{deathee} was 200 pumped by {deather}",
    f"{deathee} fell off a cliff",
    f"{deathee} bumped their head too hard",
    f"{deathee} walked into a cactus while trying to escape {deather}",
    f"{deathee} experienced kinetic energy",
    f"{deathee} got **owned**",
    f"{deathee} was killed by **intentional** game design",
    f"{deathee} tried to swim in lava",
    f"{deathee}'s heart gave up",
    f"{deathee} got themselves in a pickle",
    f"{deathee} fell out of the world",
    f"{deathee} f*cked up",
    f"{deathee} tried to backflip",
    f"{deathee} died",
    f"{deathee} was sent to the gulag by {deather}",
    f"{deathee} was killed by a f*cking vex",
    f"{deathee} listened to JoJo Siwa talk",
    f"{deathee} was poked to death by sweet berry bushes",
    f"{deathee} was **exposed**",
    "finn fell again",
    f"{deathee} died under **suspicious** circumstances",
    f"{deathee} was not the imposter",
    f"{deathee} was killed by the imposter: {deather}",
    f"{deathee} was digested",
    f"{deathee} regurgitated their heart",
    f"{deathee} went to sleep and never woke back up",
    f"{deathee} lost their liver to {deather}",
    f"{deathee} died in a climbing accident in Costa Rica",
    f"{deathee} got stuck in double english",
    f"{deathee} got **covid**",
    f"{deathee} forgot to turn the oven off",
    f"{deathee} ate too much McDonalds",
    f"{deathee} died in surgery",
    f"{deathee} cut their hand off by accident",
    f"{deathee} was abducted by aliens",
    f"{deathee} lost a bet to {deather}",
    f"{deathee} lost russian roulet",
    f"{deathee} fell up the stairs",
    f"{deathee} fell down the boatem hole",
    f"{deathee} inhaled **aspestos**",
    f"{deathee} met their demise",
    f"{deathee} got framed for triple homocide by {deather}",
    f"{deathee} ended up in Alabama",
    f"{deathee} got skinned alive by pigeons",
    f"{deathee} was snuck up on by {deather}",
    f"{deathee} was eaten by {deather}",
    f"{deathee} wacked their scooter against their shin",
    f"{deathee} snapped their tongue",
    f"{deathee} couldn't speedbridge",
    f"{deathee} bruised their lungs",
    f"{deathee} had a pigeon for a chest",
    f"{deathee} ate a seed and a tree grew",
    f"{deathee} became a donut",
    f"{deathee} went to school LOL",
    f"{deathee} got trapped in Kent",
    f"{deathee} got trapped on the south of the river",
    f"{deathee} failed to breath",
    f"{deathee} was **sus**",
    f"{deathee} was no-scoped by their granny",
    f"{deathee} touched grass",
    f"{deathee} ate christmas pudding",
    f"{deathee} went outside",
    f"{deathee} was teleported 40 metres into the air",
    f"{deathee} was assasainated by {deather}",
    f"{deathee} messed with the Italian Mafia",
    f"{deathee} speedran life",
    f"{deathee} messed with {deather}",
    f"{deathee} tried to break the world record of not blinking for 33hrs",
    f"{deathee} got unborn",
    f"{deathee} starved",
    f"{deathee} messed with JOe",
    f"{deathee} forgot the semi-colon in c#",
    f"{deathee} didn't achieve **moksha**",
    f"{deathee} asked who Candice is",
    f"{deathee} bent over in public showers",
  ]